# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
#
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     ##
      - name: Set up Git repository
        run: |
          git init
          git config user.name "Kimsw-G"
          git config user.email "kimsw3445@naver.com"
          mkdir build
          touch build/a
          ls -al ./build    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git
      - name: Install Git-FTP
        run: sudo apt-get install -y git-ftp

      - name: FTP Deploy
        run: |
          cd ${{ github.workspace }}
          git ftp init -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} sftp://${{ secrets.FTP_HOST }}
          git ftp push --force --auto-init --verbose --syncroot ./ -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} sftp://${{ secrets.FTP_HOST }}

      

