# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
#
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
 ## print value
    - name : print ftp_host 
      run: echo "${{ secrets.secrets.FTP_HOST }}"
      
 ## ftp to svr
    - name : ftp to svr
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/

 ## docker compose up
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          mkdir hi
          ## sudo docker rm -f $(docker ps -qa)
          ##sudo docker pull ${{ secrets.DOCKER_REPO }}/second-eyes-web
          ##sudo docker pull ${{ secrets.DOCKER_REPO }}/second-eyes-nginx
          ##docker-compose up -d
          ##docker image prune -f
